// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: minimax.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Board struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Grid   *Board_Grid             `protobuf:"bytes,1,opt,name=grid,proto3" json:"grid,omitempty"`
	Snakes map[uint32]*Board_Snake `protobuf:"bytes,2,rep,name=snakes,proto3" json:"snakes,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Board) Reset() {
	*x = Board{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minimax_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_minimax_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_minimax_proto_rawDescGZIP(), []int{0}
}

func (x *Board) GetGrid() *Board_Grid {
	if x != nil {
		return x.Grid
	}
	return nil
}

func (x *Board) GetSnakes() map[uint32]*Board_Snake {
	if x != nil {
		return x.Snakes
	}
	return nil
}

type ExpandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Board *Board `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
}

func (x *ExpandRequest) Reset() {
	*x = ExpandRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minimax_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandRequest) ProtoMessage() {}

func (x *ExpandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minimax_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandRequest.ProtoReflect.Descriptor instead.
func (*ExpandRequest) Descriptor() ([]byte, []int) {
	return file_minimax_proto_rawDescGZIP(), []int{1}
}

func (x *ExpandRequest) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type EvaluateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Board *Board `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minimax_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minimax_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_minimax_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluateRequest) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type CancelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minimax_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_minimax_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_minimax_proto_rawDescGZIP(), []int{3}
}

type ExpandAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ExpandAck) Reset() {
	*x = ExpandAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minimax_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandAck) ProtoMessage() {}

func (x *ExpandAck) ProtoReflect() protoreflect.Message {
	mi := &file_minimax_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandAck.ProtoReflect.Descriptor instead.
func (*ExpandAck) Descriptor() ([]byte, []int) {
	return file_minimax_proto_rawDescGZIP(), []int{4}
}

type EvaluateAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EvaluateAck) Reset() {
	*x = EvaluateAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minimax_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateAck) ProtoMessage() {}

func (x *EvaluateAck) ProtoReflect() protoreflect.Message {
	mi := &file_minimax_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateAck.ProtoReflect.Descriptor instead.
func (*EvaluateAck) Descriptor() ([]byte, []int) {
	return file_minimax_proto_rawDescGZIP(), []int{5}
}

type CancelAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelAck) Reset() {
	*x = CancelAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minimax_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAck) ProtoMessage() {}

func (x *CancelAck) ProtoReflect() protoreflect.Message {
	mi := &file_minimax_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAck.ProtoReflect.Descriptor instead.
func (*CancelAck) Descriptor() ([]byte, []int) {
	return file_minimax_proto_rawDescGZIP(), []int{6}
}

type ExpandReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Board *Board `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
}

func (x *ExpandReply) Reset() {
	*x = ExpandReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minimax_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpandReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandReply) ProtoMessage() {}

func (x *ExpandReply) ProtoReflect() protoreflect.Message {
	mi := &file_minimax_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandReply.ProtoReflect.Descriptor instead.
func (*ExpandReply) Descriptor() ([]byte, []int) {
	return file_minimax_proto_rawDescGZIP(), []int{7}
}

func (x *ExpandReply) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

type EvaluateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Score uint32 `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *EvaluateReply) Reset() {
	*x = EvaluateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minimax_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateReply) ProtoMessage() {}

func (x *EvaluateReply) ProtoReflect() protoreflect.Message {
	mi := &file_minimax_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateReply.ProtoReflect.Descriptor instead.
func (*EvaluateReply) Descriptor() ([]byte, []int) {
	return file_minimax_proto_rawDescGZIP(), []int{8}
}

func (x *EvaluateReply) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type Ready struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *Ready) Reset() {
	*x = Ready{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minimax_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ready) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ready) ProtoMessage() {}

func (x *Ready) ProtoReflect() protoreflect.Message {
	mi := &file_minimax_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ready.ProtoReflect.Descriptor instead.
func (*Ready) Descriptor() ([]byte, []int) {
	return file_minimax_proto_rawDescGZIP(), []int{9}
}

func (x *Ready) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Ready) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Board_Snake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body   []*Board_Snake_Coordinate `protobuf:"bytes,1,rep,name=body,proto3" json:"body,omitempty"`
	Health uint32                    `protobuf:"varint,2,opt,name=health,proto3" json:"health,omitempty"`
	Value  uint32                    `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Board_Snake) Reset() {
	*x = Board_Snake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minimax_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Board_Snake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board_Snake) ProtoMessage() {}

func (x *Board_Snake) ProtoReflect() protoreflect.Message {
	mi := &file_minimax_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board_Snake.ProtoReflect.Descriptor instead.
func (*Board_Snake) Descriptor() ([]byte, []int) {
	return file_minimax_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Board_Snake) GetBody() []*Board_Snake_Coordinate {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Board_Snake) GetHealth() uint32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *Board_Snake) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Board_Grid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height uint32   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Width  uint32   `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Values []uint32 `protobuf:"varint,3,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *Board_Grid) Reset() {
	*x = Board_Grid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minimax_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Board_Grid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board_Grid) ProtoMessage() {}

func (x *Board_Grid) ProtoReflect() protoreflect.Message {
	mi := &file_minimax_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board_Grid.ProtoReflect.Descriptor instead.
func (*Board_Grid) Descriptor() ([]byte, []int) {
	return file_minimax_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Board_Grid) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Board_Grid) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Board_Grid) GetValues() []uint32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type Board_Snake_Coordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X uint32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y uint32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Board_Snake_Coordinate) Reset() {
	*x = Board_Snake_Coordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_minimax_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Board_Snake_Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board_Snake_Coordinate) ProtoMessage() {}

func (x *Board_Snake_Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_minimax_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board_Snake_Coordinate.ProtoReflect.Descriptor instead.
func (*Board_Snake_Coordinate) Descriptor() ([]byte, []int) {
	return file_minimax_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Board_Snake_Coordinate) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Board_Snake_Coordinate) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_minimax_proto protoreflect.FileDescriptor

var file_minimax_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x61, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x8a, 0x03, 0x0a, 0x05, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x22, 0x0a,
	0x04, 0x67, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x62,
	0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x47, 0x72, 0x69, 0x64, 0x52, 0x04, 0x67, 0x72, 0x69,
	0x64, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x2e, 0x53, 0x6e, 0x61,
	0x6b, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x73, 0x6e, 0x61, 0x6b, 0x65, 0x73,
	0x1a, 0x8f, 0x01, 0x0a, 0x05, 0x53, 0x6e, 0x61, 0x6b, 0x65, 0x12, 0x2e, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f,
	0x61, 0x72, 0x64, 0x2e, 0x53, 0x6e, 0x61, 0x6b, 0x65, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x61, 0x6c,
	0x74, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x28, 0x0a, 0x0a, 0x43, 0x6f, 0x6f, 0x72,
	0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x01, 0x79, 0x1a, 0x50, 0x0a, 0x04, 0x47, 0x72, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12, 0x1a, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x42, 0x02, 0x10, 0x01, 0x52, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x1a, 0x4a, 0x0a, 0x0b, 0x53, 0x6e, 0x61, 0x6b, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x2e,
	0x53, 0x6e, 0x61, 0x6b, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x30, 0x0a, 0x0d, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x05, 0x62, 0x6f, 0x61,
	0x72, 0x64, 0x22, 0x32, 0x0a, 0x0f, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52,
	0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0b, 0x0a, 0x09, 0x45, 0x78, 0x70, 0x61, 0x6e,
	0x64, 0x41, 0x63, 0x6b, 0x22, 0x0d, 0x0a, 0x0b, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65,
	0x41, 0x63, 0x6b, 0x22, 0x0b, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x41, 0x63, 0x6b,
	0x22, 0x2e, 0x0a, 0x0b, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x1f, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x70, 0x62, 0x2e, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64,
	0x22, 0x25, 0x0a, 0x0d, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x2f, 0x0a, 0x05, 0x52, 0x65, 0x61, 0x64, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x32, 0xb7, 0x01, 0x0a, 0x07, 0x4d, 0x69, 0x6e,
	0x69, 0x6d, 0x61, 0x78, 0x12, 0x36, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x45, 0x78, 0x70, 0x61, 0x6e,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x70, 0x61, 0x6e, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x70,
	0x61, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x30, 0x01, 0x12, 0x39, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x2e,
	0x70, 0x62, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x62, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x11,
	0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x41, 0x63, 0x6b,
	0x22, 0x00, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6b, 0x72, 0x69, 0x73, 0x74, 0x69, 0x61, 0x6e, 0x2d, 0x64, 0x2f, 0x66, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x72, 0x2f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_minimax_proto_rawDescOnce sync.Once
	file_minimax_proto_rawDescData = file_minimax_proto_rawDesc
)

func file_minimax_proto_rawDescGZIP() []byte {
	file_minimax_proto_rawDescOnce.Do(func() {
		file_minimax_proto_rawDescData = protoimpl.X.CompressGZIP(file_minimax_proto_rawDescData)
	})
	return file_minimax_proto_rawDescData
}

var file_minimax_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_minimax_proto_goTypes = []interface{}{
	(*Board)(nil),                  // 0: pb.Board
	(*ExpandRequest)(nil),          // 1: pb.ExpandRequest
	(*EvaluateRequest)(nil),        // 2: pb.EvaluateRequest
	(*CancelRequest)(nil),          // 3: pb.CancelRequest
	(*ExpandAck)(nil),              // 4: pb.ExpandAck
	(*EvaluateAck)(nil),            // 5: pb.EvaluateAck
	(*CancelAck)(nil),              // 6: pb.CancelAck
	(*ExpandReply)(nil),            // 7: pb.ExpandReply
	(*EvaluateReply)(nil),          // 8: pb.EvaluateReply
	(*Ready)(nil),                  // 9: pb.Ready
	(*Board_Snake)(nil),            // 10: pb.Board.Snake
	(*Board_Grid)(nil),             // 11: pb.Board.Grid
	nil,                            // 12: pb.Board.SnakesEntry
	(*Board_Snake_Coordinate)(nil), // 13: pb.Board.Snake.Coordinate
}
var file_minimax_proto_depIdxs = []int32{
	11, // 0: pb.Board.grid:type_name -> pb.Board.Grid
	12, // 1: pb.Board.snakes:type_name -> pb.Board.SnakesEntry
	0,  // 2: pb.ExpandRequest.board:type_name -> pb.Board
	0,  // 3: pb.EvaluateRequest.board:type_name -> pb.Board
	0,  // 4: pb.ExpandReply.board:type_name -> pb.Board
	13, // 5: pb.Board.Snake.body:type_name -> pb.Board.Snake.Coordinate
	10, // 6: pb.Board.SnakesEntry.value:type_name -> pb.Board.Snake
	1,  // 7: pb.Minimax.GetExpansion:input_type -> pb.ExpandRequest
	2,  // 8: pb.Minimax.GetEvaluation:input_type -> pb.EvaluateRequest
	3,  // 9: pb.Minimax.RequestCancellation:input_type -> pb.CancelRequest
	7,  // 10: pb.Minimax.GetExpansion:output_type -> pb.ExpandReply
	8,  // 11: pb.Minimax.GetEvaluation:output_type -> pb.EvaluateReply
	6,  // 12: pb.Minimax.RequestCancellation:output_type -> pb.CancelAck
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_minimax_proto_init() }
func file_minimax_proto_init() {
	if File_minimax_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_minimax_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Board); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minimax_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpandRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minimax_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minimax_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minimax_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpandAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minimax_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minimax_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minimax_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpandReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minimax_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minimax_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ready); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minimax_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Board_Snake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minimax_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Board_Grid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_minimax_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Board_Snake_Coordinate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_minimax_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_minimax_proto_goTypes,
		DependencyIndexes: file_minimax_proto_depIdxs,
		MessageInfos:      file_minimax_proto_msgTypes,
	}.Build()
	File_minimax_proto = out.File
	file_minimax_proto_rawDesc = nil
	file_minimax_proto_goTypes = nil
	file_minimax_proto_depIdxs = nil
}
